spring:
  cloud:
    gateway:
      routes:
        - id: first
          uri: http://localhost:8081
          predicates:
            - Method=GET
            - Path=/first/**
          filters:
            - RewritePath=/first/(?<path>.*),/$\{path}
        - id: second
          uri: http://localhost:8082
          predicates:
            - Method=GET
            - Path=/second/**
          filters:
            - RewritePath=/second/(?<path>.*),/$\{path}